name: Test Composite Action
on:
  workflow_dispatch:

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test my composite action
        id: foo
        uses: spindev/hello-world-composite-action@v1
        with:
          who-to-greet: 'spindev'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
